### ISSUE TITLE
Without arguments

### ISSUE THREAD

**Issue by szepeviktor** [superalex/py-wetransfer#14]
Cloud you check for arguments here?
https://github.com/superalex/py-wetransfer/blob/master/wetransfer.py#L92

```
./wetransfer.py
Traceback (most recent call last):
  File "./wetransfer.py", line 108, in <module>
    main(sys.argv[1:])
  File "./wetransfer.py", line 92, in main
    if argv[0].find('http') == 0:
IndexError: list index out of range
```

**Comment by superalex** [comment]
Sure! -> https://github.com/superalex/py-wetransfer/commit/570cc654f9bc1751932697bc0514b59157b5ccd1
