### ISSUE TITLE
download_data['fields']['filename'] KeyError: 'fields'

### ISSUE THREAD

**Issue by arthurlutz** [superalex/py-wetransfer#26]
```
$ python wetransfer.py -u [snip]
Downloading [snip]
Traceback (most recent call last):
  File "wetransfer.py", line 127, in <module>
    main(sys.argv[1:])
  File "wetransfer.py", line 119, in main
    download(file_id, recipient_id, security_hash)
  File "wetransfer.py", line 36, in download
    file_name = download_data['fields']['filename']
KeyError: 'fields'
```

**Comment by christianmarth** [comment]
I'm getting the same error

**Comment by ysig** [comment]
Me too
